service: iabd-proyecto-final

provider:
    deploymentMethod: direct
    name: aws
    region: eu-west-3
    stage: prod
    runtime: python3.9
    environment:
        STRIP_STAGE_PATH: yes
        FLASK_APP: main
        FLASK_ENV: production

plugins:
    - serverless-wsgi
    - serverless-python-requirements
    - serverless-lift

custom:
    wsgi:
        app: main.app

functions:
    app:
        handler: wsgi_handler.handler
        events:
            -   httpApi: '*'

constructs:
    website:
        type: server-side-website
        assets:
            '/static/*': static
            
package:
    patterns:
        - '!static/**'
        - '!venv/**'
        - '!.idea/**'
        - '!.flaskenv'
        - '!.env'
            